Repository itering/subscan-multisig-backend, pull requests merged in 2021-01, with the labels that each got.

#1 Adding properties required at frontend in the API
  README.md
  spec/index.ts
  spec/nodemon.json
  spec/tests/storage.spec.ts
  src/crawler/getPolkadotData.ts
  src/routes/index.ts
  src/routes/wallets.ts
  src/storage.ts
  src/types/crab.ts
  src/types/darwinia.ts
  src/types/networks.ts
Labels: enhancement

#3 Feature/multiple network support
  README.md
  src/crawler/getPolkadotData.ts
  src/index.ts
  src/public/scripts/index.js
  src/public/stylesheets/style.css
  src/routes/wallets.ts
  src/storage.ts
  src/views/index.html
Labels: enhancement

#4 Feature/moving to mongodb
  .eslintrc.json
  package.json
  spec/index.ts
  spec/tests/storage.spec.ts
  src/LoadEnv.ts
  src/Server.ts
  src/crawler/getPolkadotData.ts
  src/index.ts
  src/interfaces/multisigCalls.ts
  src/routes/index.ts
  src/routes/status.ts
  src/routes/wallets.ts
  src/shared/Logger.ts
  src/shared/constants.ts
  src/shared/functions.ts
  src/storage.ts
  src/types/crab.ts
  src/types/darwinia.ts
  src/types/networks.ts
  yarn.lock
Labels: Bug-fixed, enhancement

#6 Revert "Revert "Feature/moving to mongodb""
  .eslintrc.json
  README.md
  package.json
  spec/index.ts
  spec/tests/storage.spec.ts
  src/LoadEnv.ts
  src/Server.ts
  src/crawler/getPolkadotData.ts
  src/index.ts
  src/interfaces/multisigCalls.ts
  src/routes/index.ts
  src/routes/status.ts
  src/routes/wallets.ts
  src/shared/Logger.ts
  src/shared/constants.ts
  src/shared/functions.ts
  src/storage.ts
  src/types/crab.ts
  src/types/darwinia.ts
  src/types/networks.ts
  yarn.lock
Labels: Bug-fixed, enhancement

#7 Change crawler logic
  spec/tests/storage.spec.ts
  src/crawler/getPolkadotData.ts
  src/interfaces/multisigCalls.ts
  src/routes/wallets.ts
Labels: A0-pleasereview
